[workspace]
members = ["client", "common", "server"]
resolver = "2"

[workspace.dependencies]
async-dup = "1.2.4"
common = { path = "common" }
smol = "2.0.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
