on:
        release:
                types: [created]

jobs:
        release:
                name: release ${{ matrix.target }}
                runs-on: ubuntu-latest
                strategy:
                        fail-fast: false
                        matrix:
                                package: [client, server]
                                target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
                steps:
                        - uses: actions/checkout@master
                        - name: Compile and release - Client
                          uses: rust-build/rust-build.action@latest
                          env:
                                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                          with:
                                  EXTRA_FILES: "README.md LICENSE"
                                  RUSTTARGET: ${{ matrix.target }}
                                  SRC_DIR: "client"
                        - name: Compile and release - Server
                          uses: rust-build/rust-build.action@latest
                          env:
                                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                          with:
                                  EXTRA_FILES: "README.md LICENSE"
                                  RUSTTARGET: ${{ matrix.target }}
                                  SRC_DIR: "server"
