on:
        release:
                types: [created]

jobs:
        release-client:
                name: release ${{ matrix.target }} - client
                runs-on: ubuntu-latest
                strategy:
                        fail-fast: false
                        matrix:
                          include:
                                - target: x86_64-pc-windows-gnu
                                  name: windows-amd64-client
                                - target: x86_64-unknown-linux-musl
                                  name: linux-amd64-client
                                - target: x86_64-apple-darwin
                                  name: darwin-amd64-client
                steps:
                        - uses: actions/checkout@master
                        - name: Compile and release - Client
                          uses: rust-build/rust-build.action@latest
                          env:
                                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                          with:
                                  ARCHIVE_NAME: ${{ matrix.name }}
                                  EXTRA_FILES: "README.md LICENSE"
                                  RUSTTARGET: ${{ matrix.target }}
                                  SRC_DIR: "client"

        release-server:
                name: release ${{ matrix.target }} - server
                runs-on: ubuntu-latest
                strategy:
                        fail-fast: false
                        matrix:
                          include:
                                - target: x86_64-pc-windows-gnu
                                  name: windows-amd64-server
                                - target: x86_64-unknown-linux-musl
                                  name: linux-amd64-server
                                - target: x86_64-apple-darwin
                                  name: darwin-amd64-server
                steps:
                        - uses: actions/checkout@master
                        - name: Compile and release - Server
                          uses: rust-build/rust-build.action@latest
                          env:
                                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                          with:
                                  ARCHIVE_NAME: ${{ matrix.name }}
                                  EXTRA_FILES: "README.md LICENSE"
                                  RUSTTARGET: ${{ matrix.target }}
                                  SRC_DIR: "server"
